# DATA TRANSFORMATION
In this notebook, we'll focus on engineering new features from our clean dataset in an attempt to segment customers in a way that'll help us solve the business question at hand.  
**Business Goal** - To enable the business to stop treating all customers the same and instead personalize how customers are engaged based on their value, loyalty and behaviour.
We want to decide who deserves discounts, who deserves loyalty rewards, and who deserves premium experiences - using the data, not guesswork.  
  
  In this notebook, I'll create features that bin customers into:
  1. High, medium and low value customers
  2. Discount sensitive shoppers
  3. At-risk customers

In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
import os
from sqlalchemy import create_engine

In [2]:
# Read in the data
df = pd.read_csv(r"../data/cleaned/customer_data_clean.csv")
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually

In [3]:
# Sanity Check
print(f"Dataset has {df.isnull().sum().sum()} null values")
print(f"Dataset has {df.duplicated().sum()} duplicates")

Dataset has 0 null values
Dataset has 0 duplicates

### Binary mapping of subscription status and discount application
This step converts categorical yes/no fields into binary numerical flags to make them usable for any statistical analysis or ML models if need be.

In [4]:
binary_map = {"Yes": 1, "No": 0}

df["subscription_flag"] = df["subscription_status"].map(binary_map)
df["discount_flag"] = df["discount_applied"].map(binary_map)

### Ordinal mapping of purchase requency
This step will transform purchase frequency categories into an ordinal numerical score giving higher scores to customers with more frequent engagement.  
**Weekly > Fortnightly > Monthly > Quarterly > Annually**

In [5]:
# Ordinal representation of how often customers come back to make a purchase
frequency_map = {
    "Weekly": 5,
    "Fortnightly": 4,
    "Monthly": 3,
    "Quarterly": 2,
    "Annually": 1
}

df["purchase_frequency_score"] = df["frequency_of_purchases"].map(frequency_map)

### Assign a loyalty score to each customer based on previous purchases
The logic here is to log transform a customer's previous purchases and use this as a proxy to capture their loyalty.   
I'll use the formula:    
  
  `loyalty_score = log(previous_purchases) + 1`    
  
  **Why**??  
  
  Each additional purchase does not increase loyalty linearly. So to model repeat buying, the first purchases are very critical. We need to catch the diminishing returns that come with increasing purchases. Eg -> A customer returning 50 times is no different with a customer returning 30 times. These are both loyal. On the other hand, there is a huge difference with a customer buying once and another customer buying thrice. One just made a purchase while the other is forming a habit. That's why I'll log transform the previous purchases column to catch this behaviour.  
    
**Adding 1** to the formula helps keep customers with 0 previous purchases in our dataset since *log(0)* is undefined.

In [6]:
df["loyalty_score"] = round(np.log(df["previous_purchases"] + 1), 4)

### Customer loyalty tier classification bases on previous purchases
This categorizes customers into loyalty tiers based on historical purchase counts.

In [7]:
def loyalty_tier(x):
    if x <= 1:
        return "New"
    elif x <= 10:
        return "Returning"
    else:
        return "Loyal"

df["loyalty_tier"] = df["previous_purchases"].apply(loyalty_tier)

### Purchase value tiering using purchase amount quantiles
This step assigns customers to value tiers based on their purchase amount.  
The purchase amount is divided into 3 quantiles using pandas' qcut method and label them as "LOW", "MEDIUM" or "HIGH".  
This takes into consideration the data's distribution - We are not just using arbitrary values.

In [8]:
df["value_tier"] = pd.qcut(df["purchase_amount_usd"], q=3, labels=["Low", "Medium", "High"])

### A composite value score that incorporates customer spending and loyalty.
We'll create a combined metric that incorporates both spending and loyalty by multipyling the purchase amount by 1 + the loyalty score assigned to a customer. This means that the loyalty score is a bonus to the customer's current spend. So for new customers: Value = Spend and for loyal customers: Value > Spend. I am using this as a proxy since I don't have customer's transaction history that would help me calculate their CLV.

In [9]:
df["customer_value_score"] = round((df["purchase_amount_usd"] * (1 + df["loyalty_score"])), 2)

### Review sentiment classification and risk flagging
This step will convert numerical review ratings into sentiment categories and identify at-risk customers

In [10]:
def review_sentiment(x):
    if x < 3:
        return "Low"
    elif x < 4:
        return "Neutral"
    else:
        return "High"

df["review_sentiment"] = df["review_rating"].apply(review_sentiment)

df["high_value_low_satisfaction_flag"] = np.where((df["value_tier"] == "High") & (df["review_sentiment"] == "Low"), 1, 0)

### Sanity check
Peep in to see a look of our processed dataset

In [11]:
df.tail(10)

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,season,review_rating,subscription_status,...,frequency_of_purchases,subscription_flag,discount_flag,purchase_frequency_score,loyalty_score,loyalty_tier,value_tier,customer_value_score,review_sentiment,high_value_low_satisfaction_flag
3890,3891,35,Female,Shirt,Clothing,81,Nebraska,Winter,2.6,No,...,Annually,0,0,1,3.5264,Loyal,High,366.64,Low,1
3891,3892,36,Female,Dress,Clothing,30,Colorado,Winter,4.7,No,...,Quarterly,0,0,2,1.9459,Returning,Low,88.38,High,0
3892,3893,35,Female,Jewelry,Accessories,86,Michigan,Summer,3.5,No,...,Fortnightly,0,0,4,1.7918,Returning,High,240.09,Neutral,0
3893,3894,21,Female,Hat,Accessories,64,Massachusetts,Fall,3.3,No,...,Fortnightly,0,0,4,3.4012,Loyal,Medium,281.68,Neutral,0
3894,3895,66,Female,Skirt,Clothing,78,Connecticut,Spring,3.9,No,...,Quarterly,0,0,2,3.8067,Loyal,High,374.92,Neutral,0
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,Summer,4.2,No,...,Weekly,0,0,5,3.4965,Loyal,Low,125.90,High,0
3896,3897,52,Female,Backpack,Accessories,49,Iowa,Spring,4.5,No,...,Fortnightly,0,0,4,3.7377,Loyal,Medium,232.15,High,0
3897,3898,46,Female,Belt,Accessories,33,New Jersey,Spring,2.9,No,...,Quarterly,0,0,2,3.2189,Loyal,Low,139.22,Low,0
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,Summer,3.8,No,...,Weekly,0,0,5,3.2189,Loyal,High,324.86,Neutral,0
3899,3900,52,Female,Handbag,Accessories,81,California,Spring,3.1,No,...,Quarterly,0,0,2,3.5264,Loyal,High,366.64,Neutral,0

### Save our data in a csv
We'll save our transformed data in the **data/processed/** directory that we'll make as a csv file

In [12]:
final_features = ["customer_id","age", "gender", "location", "category", "season","payment_method", "shipping_type", "purchase_amount_usd", 
                  "previous_purchases", "purchase_frequency_score", "loyalty_score", "loyalty_tier","value_tier", "customer_value_score",
                  "discount_flag", "subscription_flag", "review_rating", "review_sentiment", "high_value_low_satisfaction_flag"
                 ]
df_features = df[final_features]

# Save df as a csv
output_dir = "../data/processed"
os.makedirs(output_dir, exist_ok=True)

df_features.to_csv(os.path.join(output_dir, "customer_features.csv"), index=False)

Now that we have our data ready, we'll move to SQL in an attempt to answer some business questions based on the segments we have created here.  
We'd like to know:  
- Who are our highest-value customers?
- Are loyal customers over-discounted?
- Do subscribers generate higher value?
- Which product categories attract our most valuable and loyal customers?

In [14]:
engine = create_engine("postgresql://postgres:muthii@localhost:5432/customer_data_db")

df_features.to_sql("customer_features", engine, if_exists="replace", index=False)

900